project:
  type: website
  output-dir: docs
  render:
    - Project_1.qmd

website:
  title: "ST 558 Project 1"
  navbar:
    left:
      - href: Project_1.qmd
        text: Project 1

format:
  html:
    theme: cosmo
    toc: true